#web
gh_url: https://github.com/anxoportela
browser: chrome
account_name: anxoportela
explicit_timeout: 10s

#chrome_options
chrome_options:
  #  - --headless
  - --disable-gpu

#exceldata
excel_file: resources/testing.xlsx
excel_sheet: Web