#project
excel_file: resources/testing.xlsx
excel_sheet: Web
tests_folder: testcases
log_info: INFO

#chrome_options
chrome_options:
  #  - --headless
  - --disable-gpu

#web
gh_url: https://github.com/anxoportela
browser: chrome
account_name: anxoportela
explicit_timeout: 10s

#api
gh_api: https://api.github.com
get_users: /users

#appium
ANDROID_AUTOMATION_NAME: UIAutomator2
ANDROID_APP: C:\APKs\ApiDemos-debug.apk
ANDROID_PLATFORM_NAME: Android
ANDROID_PLATFORM_VERSION: "%{ANDROID_PLATFORM_VERSION=11}"